# Data paths configuration
raw_data_path: "data/raw/breast_cancer.csv"
processed_data_path: "data/processed/scaled_data.csv"

# Saved model path
save_model_path: "model/random_forest.joblib"

# Train/Test split parameters
test_size: 0.2
random_state: 42

# Model hyperparameters (Random Forest Classifier)
n_estimators: 100
depth: 5